<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWyc6dnl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWyc6dnl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWyc6dnl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWyc6dnl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWyc6dnl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wyc6dnl',
    'container.build_id' => '1c64ebdf',
    'container.build_time' => 1684144910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWyc6dnl');
