<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYw14HJB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYw14HJB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYw14HJB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYw14HJB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYw14HJB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yw14HJB',
    'container.build_id' => '92afd17c',
    'container.build_time' => 1684876008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYw14HJB');
