<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAhk80Dd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAhk80Dd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAhk80Dd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAhk80Dd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAhk80Dd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ahk80Dd',
    'container.build_id' => '72aab326',
    'container.build_time' => 1684152919,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAhk80Dd');
